version: "3.7"

services:

  test-service:
    container_name: test-container
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/test_repo
    depends_on:
      - localstack
    environment:
      TEST_ENV: "qa"
      LOCALSTACK_HOST: "localstack"
      LOCALSTACK_PORT: "4566"
      LOCALSTACK_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: "testuser"
      AWS_SECRET_ACCESS_KEY: "testkey"
    volumes:
      - test_repo:/home/test_repo/

  localstack:
    image: localstack/localstack:2.3.2
    environment:
      mic_path: mockserver
    ports:
      - "4566:4566"

  mockserver:
    image: mockserver/mockserver:5.15.0
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_LOG_LEVEL: TRACE
      MOCKSERVER_SERVER_PORT: 1080
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - ./config:/config

volumes:
  test_repo:
