version: "3.7"

services:

  test-service:
    container_name: test-container
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/test_repo
    depends_on:
      - localstack
    environment:
      TEST_ENV: "qa"
      LOCALSTACK_HOST: "localstack"
      LOCALSTACK_PORT: "4566"
      LOCALSTACK_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: "testuser"
      AWS_SECRET_ACCESS_KEY: "testkey"
    volumes:
      - test_repo:/home/test_repo/

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"

volumes:
  test_repo: